apiVersion: v1
kind: Pod
metadata:
  labels:
     name: jenkins-slave
spec:
  #serviceAccount: jenkins
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: busybox
      image: busybox
      command: ["tail", "-f", "/dev/null"]
      tty: true
      imagePullPolicy: Always
      nodeSelector:
        nodegroup-name: mix
#    - name: centos5
#      image: astj/centos5-vault
#      command: ["tail", "-f", "/dev/null"]
#      tty: true
#      imagePullPolicy: Always
#      nodeSelector:
#        agentpool: amilinux
    - name: windows-dotnet
        image: microsoft/nanoserver
        tty: true
      nodeSelector:
        nodegroup-name: windows-ng


#      volumeMounts:
#        - name: docker
#          mountPath: /var/run/docker.sock # We use the k8s host docker engine
#      resources:  # limits the resources your build contaienr
#        requests:
#          memory: "500Mi"
#          cpu: "250m"
#        limits:
#          memory: "1Gi"
#    - name: helm
#      image: alpine/helm
#      command: ["tail", "-f", "/dev/null"]
#      tty: true
#      imagePullPolicy: Always
# volumes:
#    - name: docker
#      hostPath:
#        path: /var/run/docker.sock