apiVersion: v1
kind: Pod
metadata:
  labels:
     name: jenkins-windows-slave
spec:
  #serviceAccount: jenkins
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: jnlp
      image: jenkins/jnlp-agent:latest-windows
      tty: true
      nodeSelector:
        kubernetes.io/os: "windows"
    - name: windows
      image: mcr.microsoft.com/dotnet/core/sdk:2.1
      tty: true
      nodeSelector:
        kubernetes.io/os: "windows"


