apiVersion: v1
kind: Pod
metadata:
  labels:
     name: jenkins-linux-slave
spec:
  #serviceAccount: jenkins
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
#    - name: centos5-go
#      image: 953835556803.dkr.ecr.us-east-1.amazonaws.com/centos5-go:1.0
#      command: ["tail", "-f", "/dev/null"]
#      tty: true
#      imagePullPolicy: IfNotPresent
    - name: goreleaser
      image: jportasa/goreleaser:1.0
      command: ["tail", "-f", "/dev/null"]
      tty: true
      imagePullPolicy: Always
    - name: busybox
      image: busybox
      command: ["tail", "-f", "/dev/null"]
      tty: true
      imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/os: "linux"
#    - name: centos5
#      image: astj/centos5-vault
#      command: ["tail", "-f", "/dev/null"]
#      tty: true
#      imagePullPolicy: Always
#      nodeSelector:
#        kubernetes.io/os: "linux"


#      volumeMounts:
#        - name: docker
#          mountPath: /var/run/docker.sock # We use the k8s host docker engine
#      resources:  # limits the resources your build contaienr
#        requests:
#          memory: "500Mi"
#          cpu: "250m"
#        limits:
#          memory: "1Gi"
#    - name: helm
#      image: alpine/helm
#      command: ["tail", "-f", "/dev/null"]
#      tty: true
#      imagePullPolicy: Always
# volumes:
#    - name: docker
#      hostPath:
#        path: /var/run/docker.sock