- name: Install Jenkins in Ubuntu18
  become: yes
  hosts: localhost

  vars:
    jenkins_hostname: jenkins.example.com
    java_packages:
      - openjdk-11-jdk

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins